// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vppcnlzbpovswfjbdmpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwcGNubHpicG92c3dmamJkbXBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwMDUzODAsImV4cCI6MjA4NTU4MTM4MH0.KBncsQt_3cTjrPIFMiCqqJu3tHk6DjIVgbukaOvC54s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});